# MetaData
sonar.organization=cesizenb3
sonar.projectKey=cesizenb3_monorepo

sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

# Langage utilisé
sonar.language=cs

# Répertoires sources et tests
sonar.sources=CESIZen
sonar.tests=CESIZen.Tests

# Couverture de code
sonar.cs.opencover.reportsPaths=coverage-report/lcov.info

# Exclusions (facultatif)
sonar.exclusions=**/wwwroot/**,**/*.cshtml

# Attente de la quality gate (optionnel, utile pour CI rapide)
sonar.qualitygate.wait=false
